words = {
    'sketch': 'Make a rough drawing of.',
    'negative': 'A word or statement that expresses denial, disagreement, or refusal.',
    'cooperate': 'Work jointly towards the same end.',
    'ball': 'A solid or hollow spherical or egg-shaped object that is kicked, thrown, or hit in a game.',
    'indoor': 'Situated, conducted, or used within a building or under cover.',
    'occupy': 'Reside or have one\'s place of business in (a building).',
    'roll': 'Move in a particular direction by turning over and over on an axis.',
    'clinic': 'An establishment or hospital department where outpatients are given medical treatment or advice, especially of a specialist nature.',
    'bundle': 'A collection of things or quantity of material tied or wrapped up together.',
    'warn': 'Inform someone in advance of a possible danger, problem, or other unpleasant situation.',
    'miss': 'Fail to hit, reach, or come into contact with (something aimed at).',
    'colleague': 'A person with whom one works in a profession or business.',
    'father': 'A man in relation to his child or children.',
    'perform': 'Carry out, accomplish, or fulfil (an action, task, or function).',
    'aware': 'Having knowledge or perception of a situation or fact.',
    'credibility': 'The quality of being trusted and believed in.',
    'superintendent': 'A person who manages or superintends an organization or activity.',
    'stimulation': 'Encouragement of something to make it develop or become more active.',
    'administration': 'The process or activity of running a business, organization, etc.',
    'compensation': 'Something, typically money, awarded to someone in recognition of loss, suffering, or injury.',
    'announcement': 'A formal public statement about a fact, occurrence, or intention.',
    'consolidate': 'Make (something) physically stronger or more solid.',
    'circulation': 'Movement to and fro or around something, especially that of fluid in a closed system.',
    'demonstrate': 'Give a practical exhibition and explanation of (how a machine, skill, or craft works or is performed).'
}